FROM node:16.13-alpine3.14 AS alpine
RUN apk --no-cache --virtual build-dependencies add \
    bash \
    git \
    openssh \
    python3 \
    make \
    g++
WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .

ARG TYPEORM_HOST
ARG TYPEORM_DATABASE
ARG TYPEORM_USERNAME
ARG TYPEORM_PASSWORD
ARG TYPEORM_CONNECTION
ARG TYPEORM_PORT
ARG TYPEORM_ENTITIES
ARG TYPEORM_MIGRATIONS
ARG NEXT_PUBLIC_IPFS_GATEWAY
ARG NEXT_PUBLIC_IPFS_API_KEY
ARG NEXT_PUBLIC_IPFS_SECRET_API_KEY
ARG NEXT_PUBLIC_IPFS_UPLOAD_ENDPOINT
ARG NEXT_PUBLIC_NETWORK_ID

ENV TYPEORM_HOST=$TYPEORM_HOST
ENV TYPEORM_DATABASE=$TYPEORM_DATABASE
ENV TYPEORM_USERNAME=$TYPEORM_USERNAME
ENV TYPEORM_PASSWORD=$TYPEORM_PASSWORD
ENV TYPEORM_CONNECTION=$TYPEORM_CONNECTION
ENV TYPEORM_PORT=$TYPEORM_PORT
ENV TYPEORM_ENTITIES=$TYPEORM_ENTITIES
ENV TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS
ENV NEXT_PUBLIC_IPFS_GATEWAY=$NEXT_PUBLIC_IPFS_GATEWAY
ENV NEXT_PUBLIC_IPFS_API_KEY=$NEXT_PUBLIC_IPFS_API_KEY
ENV NEXT_PUBLIC_IPFS_SECRET_API_KEY=$NEXT_PUBLIC_IPFS_SECRET_API_KEY
ENV NEXT_PUBLIC_IPFS_UPLOAD_ENDPOINT=$NEXT_PUBLIC_IPFS_UPLOAD_ENDPOINT
ENV NEXT_PUBLIC_NETWORK_ID=$NEXT_PUBLIC_NETWORK_ID

RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
