version: "3.8"

services:
  db:
    build:
      context: ./src/services/db
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/var/lib/redis/data
