version: "3.8"

services:
  db:
    build:
      context: ./src/services/db
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
