name: Deploy EC2
on:
  push:
    branches:
      - dockerization
  # pull_request:
  #   types: [closed]
jobs:
  deploy-app:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: unnecessary
      - name: Make script executable
        run: chmod +x ./deploy_to_aws.sh
      - name: rsync over ssh
        run: ./deploy_to_aws.sh
